### ISSUE TITLE
Support for Encrypted PEM

### ISSUE THREAD

**Issue by nmoinvaz** [kylehuff/buildcrx#6]
This is a request for support for password protected PEMs.

You'd have to call PEM_read_RSAPrivateKey with a pem_password_cb and supply it the password through userdata. 

```
printf( "usage: %s <ZIP file> <PEM file> <PEM password or \"NULL\"> (optional <OUTPUT PATH/FILE>)\n", argv[0] );

int password_cb(char *buf, int size, int rwflag, void *userdata)
{
     strcpy(buf, (char *)userdata);
     return strlen(buf);
}

if (strcmpi(argv[3], "") == 0 || strcmpi(argv[3], "NULL") == 0)
    privateKey = PEM_read_RSAPrivateKey (pemfile, NULL, NULL, NULL);
else
    privateKey = PEM_read_RSAPrivateKey (pemfile, NULL, password_cb, argv[3]);
```

**Comment by kylehuff** [comment]
Okay, I'm down, except, I question the sanity of having a password protected PEM and at the same time encouraging the practice of putting that password into the console history (and possibly the build logs). I presume the objective is to protect the PEM file in the event that the file system is accessed/breached, in which case the user's console history is probably equally accessible.

However, if the intention is to instead provide signing ability with a PEM file that just so happens to be password protected, then I would suggest perhaps having the passphrase obtained from an interactive STDIN collection method (not passed via command line), then in an automated environment the password could be obtained from dumping out a file, echoing a string or environment variable or some other hook (agent, etc), or interactively with something like pinentry - this would still have the ability to be typed onto STDIN after invocation.

Granted, all of those sources are potentially just as unsafe as passing it as a parameter, but it makes me feel like I am making people work for it. I understand that the distinction is somewhat subtle, and perhaps pedantic, but hey, I also refuse to make a turn if I don't engage my blinker in time.

What are your thoughts? My intention is not to make things difficult (the utility exists for the opposite reason!), I just want to do what makes the _most_ sense.

**Comment by nmoinvaz** [comment]
I had the same concerns about passing it in via the command line. However there exists command line utilities that do pass in the password via the command line, such as NNS signtool, so for people who need such utilities to build XPI's, they are already screwed. 

Either the PEM is not password protected or you pass in the password via the command line. Both scenarios to me seem to be as equally unsecure. The intention then would be, as you said, to provide the ability. 

I don't think adding the ability will make it any more or less difficult to use. Ideally the utility should support different argument names such as "-out my.xpi" or "-in my.zip" or "-pem my.pem", etc but that would increase the complexity of the code.

**Comment by nmoinvaz** [comment]
As for the use of STDIN; we use FinalBuilder, so that would not be an option for us as FinalBuilder doesn't support passing in information via it. So I'd end up having to do unencrypted PEM in that instance.

**Comment by kylehuff** [comment]
> I had the same concerns about passing it in via the command line. However there exists command line utilities that do pass in the password via the command line, such as NNS signtool, so for people who need such utilities to build XPI's, they are already screwed.

This is very true, however, other software also make requests for PKI passphrases via browser dialogs - I won't do that either. Such behavior sets bad precedence. Again, probably a little obstinate, but I'm inclined to not contribute to the bad practice by doing the same (which lends even more credence to it) just for the sake of what others are doing.

Yes, we are little guys in the grand scheme of things and this a very insignificant utility with a very narrow focus and application; but, "all that is necessary for evil to triumph is for good men to do nothing", as the saying goes - so if I can do it differently (even if it doesn't change the fact that other choices leave the user "already screwed"), I'd like to take that route as a matter of moral imperative.

> Either the PEM is not password protected or you pass in the password via the command line. Both scenarios to me seem to be as equally unsecure.

Seemingly, yes (although proper certificate chains in general make it possible to redress illegal key usage via revocation. I realize that this may not apply in relation to chrome extensions given that the ID is derived from the key - this should probably be raised as an issue). However, "equally unsecure" was entirely my point. Why have a password protected PEM when the password is sent (and often stored!) in clear-text. It seems to me that it makes just as much sense to not have a password at all.

> The intention then would be, as you said, to provide the ability.

Yes, I am willing to provide the ability given that the auspices are limited to, "I have a key that I need to use that just so happens to have a password".

> I don't think adding the ability will make it any more or less difficult to use.

Yes, I agree with you. I did not mean to imply this feature would make things more difficult; I meant to convey that I am not trying to be an obstructionist with my objections, merely trying to implement it sanely.

I have kind of a development modus operandi, and part of that is to always challenge "common practice". I don't want that to mean "challenge industry standard", but the way that things have "ended up" over time. For example, it is common to find software written only Windows or only Mac, or only Linux, etc. -- I reject this notion. I only write cross-platform software. One shouldn't be precluded from using buildcrx simply because they use one platform, when I use something else -- and this is what I interpret "Free Software" to actually be.

> Ideally the utility should support different argument names such as "-out my.xpi" or "-in my.zip" or "-pem my.pem", etc but that would increase the complexity of the code.

Yes, that is ideal. I don't think it would be terrible to implement, but I doubt I would attempt to tackle it any time very soon. We can add it to the wish-list though.

> As for the use of STDIN; we use FinalBuilder, so that would not be an option for us as FinalBuilder doesn't support passing in information via it.

Does FinalBuilder not allow you pipe to STDIN within the build command?

i.e. `echo $ENV_VAR_PW | buildcrx.exe .....`

> So I'd end up having to do unencrypted PEM in that instance.

Well, someone once described that either option is pretty much a zero sum game; in fact they said "Both scenarios to me seem to be as equally unsecure."  =c )

Seriously though, if the option is indeed needed and we can't find an acceptable alternative, I propose the CLI option nomenclature be '--iacceptthispasswordisvisible <the password>' (or something else ridiculous)

**Comment by nmoinvaz** [comment]
You bring up a good point about the certificate revocation list. I've never had to go through the task of revoking a certificate because a certificate was hi-jacked, hopefully will never have to.

I bet I can get away with doing something like that in FinalBuilder. If all else fails it could be some sort of batch script that gets called. I thought I'd also mention that FinalBuilder also has an option for certain actions so you can specify whether or not you want those actions to end up in the log. So for actions where passing in the password is necessary those can be hidden from the log.

I agree with the rest of what you are saying.
